# Generated by Django 4.2.7 on 2024-04-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Кот', 'verbose_name_plural': 'Коты'},
        ),
    ]
